app/dashboard/forms.py
from sre_constants import RANGE_UNI_IGNORE
from app.models import User 

from wtforms.fields import (
    StringField,
    PasswordField, 
    TextAreaField,
    SubmitField,
    MultipleFileField,
    BooleanField
)

from wtforms.validators import (
    DataRequired, 
    Length, 
    EqualTo, 
    ValidationError,
)

from flask_wtf.file import (
    FileAllowed, 
    FileField, 
    FileRequired
)
from app.models import User 

from flask_wtf import FlaskForm
from flask_login import current_user
from werkzeug.utils import secure_filename
from app.utils import EMAIL_REGEX
import re 

from app.auth.forms import RegistrationForm

    


class ChangePassword(FlaskForm):

    """
    making form for change password 
    """
    password = PasswordField('enter your password',validators=[DataRequired()])

    new_password = PasswordField('new password ', validators=[
        EqualTo('confirm_password'),
        DataRequired(message='new password is required'),
        Length(min=6, max=125, message='new password length must be between 6 to 125 characters')])

    confirm_password = PasswordField('confirm password')
    submit = SubmitField('change password')

    def validate_password(self, password_field):
        if not current_user.check_password(password_field.data):
            raise ValidationError("invalid old password")

class BlogForm(FlaskForm):
    title = StringField('Title Blog',
        validators=[
            DataRequired('fill this form'),
            Length(min=15, max=125)
        ]
    )
    body_content = TextAreaField("make some awesome things")
    thumbnail = FileField('image',
        validators=[
            FileRequired(message='file required'),
            FileAllowed(['jpg','jpeg','png'], message='only images are allowed')
        ]
    )

    submit = SubmitField("Submit")

    def validate_body_content(self, body_field):
        if len(str(body_field.data).split()) < 10:
            raise ValidationError('too short for body content (minimal 10 words) ')

class ImageForm(FlaskForm):

    imgs = MultipleFileField('images',
            render_kw={'multiple':True},
            validators=[

                FileAllowed(['jpg','png','jpeg'], message='only images are allowrd')
            ]
    )    
    submit = SubmitField('upload')

class AccountForm(FlaskForm):
    name = StringField(
        label='Full Name', 
        validators=[
            DataRequired('fill this form'),
            Length(min=5, max=100, message='name length must be between 5 to 100 characters')
        ]
    )
    username = StringField(
        label='username',
        validators=[
            DataRequired('fill your username'), 
            Length(min=5, max=100)
        ]
    )
    email = StringField( 
        label='email', 
        validators=[DataRequired()])

    submit = SubmitField()
    def validate_email(self, email_field):

        current_email = current_user.email 
        check_email = User.query.filter_by(email=email_field.data).first()
        
        if not re.match(EMAIL_REGEX, email_field.data):
            raise ValidationError('invalid email')
        
        if current_email != email_field.data:
            if check_email and check_email.email != current_email:
                raise ValidationError('email already used')

    def validate_username(self, username_field):

        current_username = current_user.username
        check_username = User.query.filter_by(username=username_field.data).first()

        if re.match('[A-Z]', username_field.data):
            raise ValidationError('invalid username, dont use uppercase to your username')
        
        if username_field.data != current_username:
            if check_username and check_username.username != current_username:
                raise ValidationError('username already used')

class AddAccount(RegistrationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    admin = BooleanField(label='is admin')
    submit = SubmitField('Submit')

    

app/dashboard/__init__.py
from flask import Blueprint

dashboard_blueprint = Blueprint('dashboard', __name__, url_prefix='/dashboard')

# import all route from dashboard
from .views import *
from .admin import *
from .errors import *

app/dashboard/views.py
import re, os
from flask.globals import current_app
from flask_login.utils import login_user
from werkzeug.exceptions import abort 
from werkzeug.utils import secure_filename
from wtforms.widgets.core import CheckboxInput
from config import GeneralConfig


from app.dashboard import dashboard_blueprint as dash 

from flask_login import (
    login_required, 
    logout_user, 
    current_user
)

from flask import ( 
    request,
    redirect,
    url_for,
    render_template,
    flash,
    Markup,
    Response
)

from app.utils import validate_image
from .forms import ( 
    ChangePassword, 
    BlogForm, 
    AccountForm, 
    ImageForm
)

from app.models import Category, User, Post, Image

''''
route for all users include admin 

'''
@dash.route('/welcome')
@login_required
def dashboard_index():
    return render_template('dashboard/index.html')

@dash.route('/logout')
@login_required
def logout_page():
    logout_user()
    return redirect(url_for('main.index_page'))

@dash.route('/account', methods=['GET','POST'])
@login_required
def account_page():
    form = AccountForm()
    
    if request.method == 'POST':
        if form.validate_on_submit():
            current_user.email = form.email.data 
            current_user.full_name = form.name.data 
            current_user.username = form.username.data 
            current_user.save()
            flash('ok')
        else:
            flash(form.errors, category='error_forms')
    
    # set value type

    form.name.data = current_user.full_name
    form.username.data = current_user.username 
    form.email.data = current_user.email

    return render_template('dashboard/account.html', form=form)

@dash.route('/change-password', methods=['GET','POST'])
@login_required
def change_password():
    form = ChangePassword()
    if request.method == 'POST':
        if form.validate_on_submit():
            new_password = form.new_password.data 
            if current_user.check_password(new_password):
                flash('you entering an old password, enter a new password')
            else:
                current_user.set_password(new_password)
                current_user.save()
                flash('password changed!')
        else:
            flash(form.errors, category='error_forms')
        
    return render_template('dashboard/change-password.html', form=form)

@dash.route('/add-blog', methods=['POST','GET'])
@login_required
def add_blog():
    form = BlogForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            body_content = form.body_content.data
            thumbnail_name = form.thumbnail.data
            new_thumbnailname = secure_filename(thumbnail_name.filename)
            title = form.title.data 

            thumbnail_name.save(os.path.join(GeneralConfig.DIR_UPLOADS, new_thumbnailname))
            
            p = Post(title=title, content=body_content, image_name=new_thumbnailname)
            p.author = current_user
            p.save()
            
            category_id = request.form['category_post']

            c = Category.query.filter_by(id=category_id).first()
            c.postingan.append(p)
            c.save()

            flash('blog added')

        else:
            flash(form.errors, category='error_forms')
    return render_template('dashboard/add-blog.html', 
                            form=form, 
                            categories=enumerate(Category.query.all()))

@dash.route('/add-images', methods=['POST','GET'])
@login_required
def add_images():
    form = ImageForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            list_images = form.imgs.data 
            list_uploaded = []
            for images in list_images:
                # validate images extensions and secure file name
                if validate_image(images):
                    new_filename = secure_filename(images.filename)
                    list_uploaded.append(new_filename)
                    images.save(os.path.join(GeneralConfig.DIR_UPLOADS,new_filename))

                    # add image to db
                    i = Image(image_name=new_filename)

                    i.image_author = current_user
                    i.save()
                    
                    list_uploaded.append(new_filename)

            uploaded = Markup('<br>uploaded '.join(list_uploaded))
            flash(uploaded)
            list_uploaded.clear()
        else:
            flash(form.errors, category='error_forms')

    return render_template('dashboard/add-images.html', form=form)

@dash.route('/blog', methods=['GET','POST'])
@login_required
def blog():
    if request.method == 'POST':
        selected_posts = request.form.getlist('checked[]')
        if len(request.form['opt']) < 4 and len(selected_posts) != 0:
            for posts_id in selected_posts:
                check_exist = Post.query.filter_by(id=posts_id).first()
                if check_exist and current_user.is_admin\
                    or check_exist.author.username == current_user.username:
                    if request.form['opt'] == '1':
                        check_exist.delete()
                        flash('{} deleted'.format(posts_id))
                else:
                    flash('oops.. somethings wrong ')
        else:
            flash('select blogs and option please')

    # if is admin, show all posts by users
    if not current_user.is_admin:
        posts = Post.query.filter_by(user_id=current_user.id).all()
    else:
        posts = Post.query.all()
    return render_template('dashboard/blog.html', posts=posts)

@dash.route('/edit-blog/<int:blog_id>', methods=['GET','POST'])
@login_required
def edit_blog(blog_id):
    check = Post.query.filter_by(id=blog_id).first()
    if check and current_user.is_admin\
        or check.author.username == current_user.username:
        form = BlogForm()

        if request.method == 'POST':
            if form.validate_on_submit():
                thumbnail_image = form.thumbnail.data 
                if validate_image(thumbnail_image):
                    check.title = form.title.data 
                    check.content = form.body_content.data 
                    new_filename = secure_filename(thumbnail_image.filename)
                    form.thumbnail.data.save(os.path.join(GeneralConfig.DIR_UPLOADS, new_filename))

                    check.image_name = new_filename

                    if len(check.post_cat) != 0:
                        print('deleting category before ..')
                        check.post_cat = []

                    if check.image_name != new_filename:
                        file_before = os.path.join(GeneralConfig.DIR_UPLOADS, check.image_name)
                        if os.path.exists(file_before):
                            os.remove(file_before)
                    check.save()

                    cat_id = request.form['category_post']
                    c = Category.query.filter_by(id=cat_id).first()
                    c.postingan.append(check)
                    c.save()
                    flash('edited')
                
                else:
                    flash('invalid image')
            
            else:
                flash(form.errors, category='error_forms')
        
        form.title.data = check.title 
        form.body_content.data = check.content

        return render_template('dashboard/add-blog.html', form=form, categories=enumerate(Category.query.all()))
    else:
        flash('blog not found?!')
        return render_template('dashboard/blog.html')

@dash.route('/delete-blog/<int:blog_id>')
@login_required
def delete_blog(blog_id):
    check = Post.query.filter_by(id=blog_id).first()
    if check and current_user.is_admin\
        or current_user.username == check.author.username:
        check.delete()
        flash('deleted')
    else:
        flash('oopss.. something wrong?')
    return redirect(url_for('dashboard.blog'))

@dash.route('/delete-image/<int:image_id>')
@login_required
def delete_image(image_id):
    check = Image.query.filter_by(id=image_id).first()
    if check:
        if current_user.id == check.user_id\
            or current_user.is_admin:
            check.delete()
            flash('deleted')
    return redirect(url_for('dashboard.show_images'))

@dash.route('/images', methods=['GET','POST'])
@login_required
def show_images():
    if request.method == 'POST':
        lists_images = request.form.getlist('checkimage[]')
        if len(lists_images) != 0 and request.form['opt_img'] == '1':
            for image_id in lists_images:
                check_image = Image.query.filter_by(id=image_id).first()
                if check_image and check_image.user_id == current_user.id\
                    or current_user.is_admin:
                    check_image.delete()
                    flash(Markup('<br>deleted {}'.format(image_id)))
                else:
                    flash('something went wrong')
        else:
            flash('something went wrong')
    if current_user.is_admin:
        image = Image.query.all()
    else:
        image = Image.query.filter_by(user_id=current_user.id)
    return render_template('dashboard/images.html', image=enumerate(image))

@dash.route('/img-ckeditor')
@login_required
def img_ckeditor():
    if current_user.is_admin:
        images = Image.query.all()
    else:
        images = Image.query.filter_by(user_id=current_user.id)
    return render_template('dashboard/list-images.html', images=enumerate(images))

app/templates/dashboard/account.html
<html>
    <head>
        {% include 'head.html' %}
    </head>
<body>
    {% include 'dashboard/menu.html'%}
    <form action='' method='POST'>
        {% include 'pesan.html'%}
        {{form.hidden_tag()}}
        <label for='name'>Name </label>
        <p>{{form.name}}</p>
        <label for='username'>Username</label>
        <p>{{form.username}}</p>
        <label for='email'>Email</label>
        <p>{{form.email}}</p>
        <p>{{form.submit}}</p>
        {% include 'script.html' %}
    </form>
</body>
</html>

app/templates/dashboard/add-account.html
<html>
    <head>
        {% include 'head.html' %}
    </head>
<body>
    {% include 'dashboard/menu.html' %}
    <form method='POST'>
        {% include 'pesan.html' %}
        {{form.hidden_tag()}}
        <label for='name'>Name</label>
        <p>{{form.name(placeholder='Full Name')}}</p>
        <label for='username'>Username</label>
        <p>{{form.username(placeholder='Username')}}</p>
        <label for='email'>Email</label>
        <p>{{form.email(placeholder='email')}}</p>
        <label for='password'>Password</label>
        <p>{{form.password(placeholder='password')}}</p>
        <label for='password_confirmation'>Confirm Password</label>
        <p>{{form.password_confirmation(placeholder='confirm password')}}</p>
        <label for='show_password'>Show Password</label>
        <p>{{form.show_password}}</p>
        <p>Is admin : {{form.admin}}</p>
        <p>{{form.submit}}</p>
    </form>
    {% include 'script.html' %}
</body>
</html>

app/templates/dashboard/add-blog.html
<html>
    <head>
        {% include 'head.html' %}
        <script src="https://cdn.ckeditor.com/4.16.2/standard-all/ckeditor.js"></script>
    </head>
<body>
    {% include 'dashboard/menu.html' %}
    <div class='container'>
        <form action='' method='POST' enctype="multipart/form-data">
            {% include 'pesan.html' %}
            {{form.hidden_tag()}}
            <p>{{form.thumbnail()}}</p>
            <p>{{form.title(placeholder='Title')}}</p>
            <p>{{form.body_content(id='editor')}}</p>
            <p>Categories
                <p>
                <select name='category_post'>
                {% for id, category in categories %}
                
                    <option value='{{category.id}}'>{{category.name}}</option>
                    
                {% endfor %}
                </select>
                </p>
            </p>
            <p>{{form.submit(class='btn btn-outline-dark')}}</p>
           
            <script>
                CKEDITOR.replace('editor', {
                    filebrowserBrowseUrl: '/dashboard/img-ckeditor',
                })
                CKEDITOR.on('instanceReady', function(evt) {
                    evt.editor.dataProcessor.htmlFilter.addRules({
                        elements: {
                            img: function(el){
                                el.addClass('img-fluid'),
                                el.addClass('mb-5'),
                                el.addClass('rounded')
                            }
                        }
                    })
                })

            </script>
            
        </form>
    </div>
    {% include 'script.html'%}

</body>
</html>

app/templates/dashboard/add-category.html
<html>
    <head>
        {% include 'head.html' %}
    </head>
<body>
    {% include 'dashboard/menu.html' %}
    
    <div class='container'>
             <form method='POST' action='{{url_for("dashboard.add_newcategory")}}'>
                 {% include 'pesan.html' %}
                <p><a href='#' id='addcat'>+ add more</a></p>
                <input type='text' name='category[]' placeholder="category name" class='mb-3'>
                <div id='add_cat'></div>
                <p><button type='submit' class='btn btn-outline-success'>Submit</button></p>
            </form>
    </div>
    {% include 'dashboard/script.html' %}
</body>
</html>

app/templates/dashboard/add-images.html
<html>
    <head>
        {% include 'head.html' %}
    </head>
<body>
    {% include 'dashboard/menu.html' %}
    <form action='' method="POST" enctype="multipart/form-data">
        {% include 'pesan.html' %}
        {{form.hidden_tag()}}
        <p>{{form.name}}</p>
        <p>{{form.imgs}}</p>
        <p>{{form.submit(class='btn btn-outline-dark')}}</p>
    </form>
    {% include 'script.html' %}
</body>
</html>

app/templates/dashboard/blog.html
<html>
    <head>
        {% include 'head.html' %}
    </head>
<body>
    {% include 'dashboard/menu.html' %}
    <form method='POST'>
        {% include 'pesan.html'%}
        <table class='table table-responsive-sm table-borderless'>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                <tr>
                    <td>
                        <input type='checkbox' name='checked[]' value='{{post.id}}'>
                    </td>
                    <td>{{post.title}}</td>
                    <td>
                        <a href='{{url_for("dashboard.edit_blog", blog_id=post.id)}}' class='item-menu'>
                            <span class='material-icons text-dark'>create</span>
                        </a>
                        <a href='{{url_for("dashboard.delete_blog", blog_id=post.id)}}' class='item-menu text-danger'>
                            <span class='material-icons'>delete</span>
                        </a>
                    </td>
                </tr>
                {% endfor %}
           

            </thead>
            </tbody>
            
        </table>
        <select name='opt'>
            <option selected>Option</option>
            <option value='1'>Delete</option>
        </select>
        <input type='submit' value='Submit'>
    </form>
    {% include 'script.html' %}
</body>
</html>

app/templates/dashboard/category.html
<html>
    <head>
        {% include 'head.html' %}
    </head>
    {% include 'dashboard/menu.html' %}
    <div class='container'>
        {% include 'pesan.html' %}
        <table class='table table-responsive-sm table-borderless'>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <form method="POST">
                <tbody>

                    {% for id, category in categories %}
                    <tr>
                        <td>
                            <input type='checkbox' name='checkcat[]' value='{{category.id}}'>
                        </td>
                        <td>
                            {{category.name}}
                        </td>
                        <td>
                            <a href='#' class='item-menu text-dark'>
                                <span class='material-icons'>create</span>
                            </a>
                            <a href='#' class='item-menu text-danger'>
                                <span class='material-icons'>delete</span>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                <thead>
                    
                    <th>
                        <select name='option_cat'>
                            <option selected>Option</option>
                            <option value='1'>Delete</option>
                        </select>
                        <input type='submit' class='btn btn-outline-dark' value='Submit'>
                    </th>
                </thead>
            </form>
        </table>
    </div>
    {% include 'dashboard/script.html' %}
</html>

app/templates/dashboard/change-password.html
<html>
    <head>
        {% include 'head.html' %}
    </head>
<body>
    {% include 'dashboard/menu.html' %}
    <div class='container'>
        <form method="POST">
            {% include 'pesan.html' %}
            {{form.hidden_tag()}}
            <p>{{form.password(placeholder='Enter your old password')}}</p>
            <p>{{form.new_password(placeholder='enter your new password')}}</p>
            <p>{{form.confirm_password(placeholder='confirm your new password')}}</p>
            <p>{{form.submit(class='btn btn-outline-dark')}}</p>
        </form>
    </div>
</body>
</html>

app/templates/dashboard/images.html
<html>
    <head>
        {% include 'head.html' %}
    </head>
<body>
    {% include 'dashboard/menu.html' %}
    <form method='POST'>
        {% include 'pesan.html' %}
        <table class='table table-responsive-sm table-borderless'>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Image</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for id, images in image %}
                <tr>
                    <td>
                        <input type='checkbox' name='checkimage[]' value='{{images.id}}'>
                    </td>
                    <td>
                        <img src='{{url_for("static", filename="img/{}".format(images.image_name))}}' class='img-thumbnail' style="max-height:100px">
                    </td>
                    <td>
                        <a href='{{url_for("dashboard.delete_image", image_id=images.id)}}' class='text-danger'>
                            <span class='material-icons'>delete</span>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <select name='opt_img'>
            <option value='1'>Delete</option>
        </select>
        <button type='submit' class='btn btn-outline-dark'>Submit</button>
    </form>
    {% include 'script.html' %}

    </script>
</body>
</html>

app/templates/dashboard/index.html
<html>
    <head>
        {% include 'head.html' %}
        
    </head>
<body>
    {% include 'dashboard/menu.html' %}
    {% include 'script.html' %}


</body>
</html>

app/templates/dashboard/list-images.html
<html>
    <head>
        {% include 'head.html' %}
        <script src="https://cdn.ckeditor.com/4.16.2/standard-all/ckeditor.js"></script>
    </head>
<body>
    {% include 'dashboard/menu.html' %}
    <div class='container'>
        <p class='mt-4'>Click Image to choose in ckeditor</p>
        <div class='row'>
            {% for id, image in images %}
                <div class='col-md-3'>
                    <img src='{{url_for("static", filename="img/{}".format(image.image_name))}}' class='img-thumbnail m-3' onclick="clickimage(this)">
                </div>
            {% endfor %}
        </div>
    </div>
    {% include 'script.html' %}
    <script type='text/javascript'>
                  function getUrlParam( paramName ) {
            var reParam = new RegExp( '(?:[\?&]|&)' + paramName + '=([^&]+)', 'i' );
            var match = window.location.search.match( reParam );

            return ( match && match.length > 1 ) ? match[1] : null;
        }
        function clickimage(img){
            var funcNum = getUrlParam('CKEditorFuncNum')
            window.opener.CKEDITOR.tools.callFunction(funcNum, img.src);
            window.close()
        }
    </script>
</body>
</html>

app/templates/dashboard/menu.html
<div class='container'>
    <div class='menu'>
        

        <link href='{{url_for("static", filename="css/dash.css")}}' rel='stylesheet'>
        {% extends 'navbar.html' %}

        {% block brand %}
            <a href='{{url_for("dashboard.dashboard_index")}}' class='navbar-brand text-dark'>Dashboard</a>
        {% endblock %}
        {% block navlink %}
            <li class='nav-item dropdown'>
                <a href='#' data-toggle='dropdown' class='nav-link' id='blogdropdown' role='button'  >Blog</a>
                <div class='dropdown-menu' aria-labelledby="blogdropdown">
                    <a href='{{url_for("dashboard.add_blog")}}' class='nav-link'>Add Blog</a>
                    <a href='{{url_for("dashboard.blog")}}' class='nav-link'>Edit Blog</a>
                    {% if current_user.is_admin %} 
                    <a href='{{url_for("dashboard.add_category")}}' class='nav-link'>Add category</a>
                    <a href='{{url_for("dashboard.category_page")}}' class='nav-link'>Edit category</a>
                    {% endif %}
                </div>
            </li>
            <li class='nav-item dropdown'>
                <a href='#' data-toggle="dropdown" class='nav-link' id='dropdownimage' role='button'>
                    Images
                </a>
                <div class='dropdown-menu' aria-labelledby="dropdownimage">
                    <a href='{{url_for("dashboard.add_images")}}' class='nav-link'>Add Images</a>
                    <a href='#' class='nav-link'>Edit/Delete Images</a>

                </div>
            </li>
            {% if current_user.is_admin %}
            <li class='nav-item dropdown'>
                <a href='#' data-toggle="dropdown" class='nav-link' id='dropdownuser' role='button'>
                    Users
                </a>
                <div class='dropdown-menu' aria-labelledby="dropdownuser">
                    <a href='{{url_for("dashboard.add_user")}}' class='nav-link'>Add Users</a>
                    <a href='{{url_for("dashboard.show_users")}}' class='nav-link'>Edit Users</a>
                </div>
            </li>
            {% endif %}
            <li class='nav-item dropdown'>
                <a href='#' data-toggle="dropdown" class='nav-link' id='dropdownaccount' role='button'>
                    Account
                </a>
                <div class='dropdown-menu' aria-labelledby="dropdownaccount">
                    <a href='{{url_for("dashboard.account_page")}}' class='nav-link'>General Settings</a>
                    <a href='{{url_for("dashboard.change_password")}}' class='nav-link'>Change Password</a>
                    <a class='nav-link' href='{{url_for("dashboard.logout_page")}}'>Logout</a>
                </div>
            </li>
    </div>
    
    {% endblock %}
    
</div> 

app/templates/dashboard/script.html
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src='{{url_for("static", filename="js/dashboard.js")}}' type='text/javascript'></script>

app/templates/dashboard/show-users.html
<html>
    <head>
        {% include 'head.html' %}
    </head>
<body>
    {% include 'dashboard/menu.html' %}
            <form method="POST" action=''>
                {% include 'pesan.html' %}
                <table class='table table-responsive-sm table-borderless w-100'>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Username</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for id, user in list_users %}
                        <tr>
                            
                            <td>
                                <input type='checkbox' name='checkbox[]' value='{{user.username}}'>
                            </td>
                            <td>{{user.username}}</td>
                            <td>
                                <a href='{{url_for("dashboard.edit_user", user_id=user.id)}}' class='item-menu'>
                                    <span class='material-icons'>create</span>
                                </a>
                                <a href='{{url_for("dashboard.delete_user", user_id=user.id)}}' class='item-menu text-danger'>
                                    <span class='material-icons'>delete</span>
                                </a>
                            </td>
                            
                        </tr>
                        {% endfor %}
                    </tbody>
                           
                </table>
                <select name='opt'>
                    <option selected>Option</option>
                    <option value='1'>Delete</option>
                    <option value='2'>Promote to admin</option>
                    
                </select>
                <input type='submit' value='Submit'>
                
            </form>
    {% include 'script.html' %}
</body>
</html>